name: terraria-container

services:
    terraria:
        image: ghcr.io/taytom258/terraria-container:dev
        environment:
            - PUID=1012
            - PGID=1012
            - WORLD=/opt/terraria/test.wld
            - TZ=America/New_York
            - VERSION=latest
            - TSVERSION=latest
            - TYPE=tshock
        network_mode: "host"
        tty: true
        stdin_open: true
        volumes:
            - terraria:/data:z
        pull_policy: always

volumes:
  terraria: